baseurl = "http://docs.greenbrick-media.com/"
languageCode = "en-us"
title = "Greenbrick Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Carlos Cash"
	description = "Learn marketing by the man himself."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/iamlos/greenbrick-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "iamlos"
	github  = "iamlos"


[[menu.main]]
	name   = "Greenbrick Docs"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Obtaining Services"
	url    = "services/"
	weight = 20

[[menu.main]]
	name   = "Negotiating Deals"
	url    = "deals/"
	weight = 30

[[menu.main]]
	name   = "Products"
	url    = "products/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true